blogging/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blogs.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogs.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap')
]

blogs/urls.py
from .feeds import LatestPostFeed
from django.urls import path
from blogs import views

app_name = 'blogs'
urlpatterns = [
    path('', views.post_list, name='posts'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='detail'),
    path('<int:post_id>/share/', views.post_share, name='share'),
    path('tag/<slug:tag_slug>/', views.post_list, name='posts_by_tag'),
    path('feed/', LatestPostFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

blogs/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from taggit.managers import TaggableManager


# Create your models here.

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='draft')
    objects = models.Manager()
    published = PublishedManager()

    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def get_absolute_url(self):
        return reverse("blogs:detail", args=[self.publish.year, self.publish.month, self.publish.day,
                                             self.slug])

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'comment by {self.name} on {self.post}'

blogs/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=50)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']


class SearchForm(forms.Form):
    query = forms.CharField()

blogs/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from .forms import EmailPostForm, CommentForm, SearchForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchRank, SearchQuery
from django.contrib.postgres.search import TrigramSimilarity

# Create your views here.


def post_list(request, tag_slug=None):
    object_list = Post.published.all().order_by("-publish")
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog.html', {'page': page, 'posts': posts, 'tag': tag})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()
    post_tags_ids = post.tags.values_list('id', flat=True)
    similiar_posts = Post.objects.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similiar_posts = similiar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
    return render(request, 'detail.html', {'post': post,
                                           'comments': comments,
                                           'new_comment': new_comment,
                                           'comment_form': comment_form,
                                           'similiar_posts': similiar_posts})


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read {post.title}"
            message = f"Read {post.title} at {post_url} \n\n {cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'admin@gmail.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'share.html', {'post': post, 'form': form, 'sent': sent})


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', weight='A') + SearchVector('body', weight='B')
            search_query = SearchQuery(query)
            results = Post.objects.annotate(
                similiarity = TrigramSimilarity('title', query),
            ).filter(similiarity__gt=0.1).order_by('-similiarity')

            # results = Post.objects.annotate(
            #     search=search_vector,
            #     rank= SearchRank(search_vector, search_query)).filter(search=search_query).order_by('-rank')
    return render(request, 'search.html', {'form': form, 'query': query, 'results': results})

templates/base.html
{% load blogs_tags %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'css/blog.css' %}" rel="stylesheet">
</head>
<body>
<div id="content">
  {% block content %}
  {% endblock %}

</div>
<div id="sidebar">
    <h2>My blog</h2>
    <p>This is my blog, There are {% total_count %} posts so far.</p>
    <p><a href="{& url 'blogs:post_feed' %}">Subscribe to my rss feed</a></p>
    <h3>Latest Posts</h3>
    {% show_latest 3 %}
    <h3>Most commented post</h3>
    {% most_commented_post 3 as most_comment %}
    <ul>
        {% for post in most_comment %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
        {% endfor %}
    </ul>
</div>
</body>
</html>

templates/blog.html
{% extends 'base.html' %}
{% load blogs_tags %}
{% block title %} My blogs {% endblock %}
{% block content %}
<h1>My blog</h1>

{% if tag %}
<h2>Posts tagged with "{{tag.name}}"</h2>
{% endif %}


{% for post in posts %}
<h2>
<a href="{{ post.get_absolute_url }}">{{post.title}}</a>
</h2>
<p class="tags">
    Tags:
    {% for tag in post.tags.all %}
    <a href="{% url 'blogs:posts_by_tag' tag.slug %}">{{tag.name}}</a>
    {% if not forloop.last %} {% endif %}
    {% endfor %}
</p>
<p class="date">Published : {{ post.publish }} by {{ post.author }}</p>
{{ post.body|markdown|truncatewords_html:30 }}
{% endfor %}

{% include 'pagination.html' with page=posts %}
{% endblock %}

templates/detail.html
{% extends 'base.html' %}
{% load blogs_tags %}
{% block title %} {{post.title}} {% endblock %}
{% block content %}
<h1>{{post.title}}</h1>

<p class="date">Published : {{ post.publish }} by {{ post.author }}</p>
{{ post.body|markdown }}
<p>
    <a href="{% url 'blogs:share' post.id %}">Share this post</a>
</p>
<h2>Similiar posts</h2>
{% for post in similiar_posts %}
<p>
    <a href="{{ post.get_absolute_url }}">{{post.title}}</a>
</p>
{% empty %}
 There are no similiar posts yet.
{% endfor %}
{% with comments.count as total_comments %}
<h2>
    {{ total_comments }} comment{{ total_comments|pluralize }}
</h2>
{% endwith %}

{% for comment in comments %}
<div class="comment">
    <p class="info">
        Comment {{ forloop.counter }} by {{ comment.name }}
        {{ comment.created }}
    </p>
    {{ comment.body|linebreaks }}
</div>
{% empty %}
<p> There are no comments yet.</p>
{% endfor %}


{% if new_comment %}
<h2>Your comments has been added.</h2>
{% else %}
<h2>
    Add a new comment
</h2>
<form method="post">
    {{ comment_form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Add comment"></p>
</form>
{% endif %}
{% endblock %}

templates/latest_post.html
<ul>
  {% for post in latest_post %}
  <li>
    <a href="{{post.get_absolute_url}}">{{post.title}}</a>
  </li>
  {% endfor %}
</ul>

templates/pagination.html
<div class="pagination">
    <span class="step_links">
        {% if page.has_previous %}
        <a href="?page={{page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
        <a href="?page={{page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>

templates/search.html
{% extends 'base.html' %}
{% load blogs_tags %}
{% block title %}Search {% endblock %}
{% block content %}
{% if query %}
<h1>Posts containing "{{ query }}"</h1>
<h3>
    {% with results.count as total_results %}
    Found {{total_results}} result {{total_results|pluralize}}
    {% endwith %}

</h3>
{% for post in results %}
<h4><a href="{{post.get_absolute_url}}">{{post.title}}</a></h4>
{{ post.body |markdown|truncatewords_html:5 }}

{% empty %}
<p>There are no results for your querry.</p>
{% endfor %}

<p><a href="{% url 'blogs:post_search' %}">Search again </a></p>
{% else %}
<h1>Search for posts </h1>
<form method="get">
    {{form.as_p }}
    <input type="submit" value="Search">

</form>

{% endif %}
{% endblock %}

templates/share.html
{% extends 'base.html' %}
{% block title %} Share a post {% endblock %}

{% block content %}
{% if sent %}
<h1>Email successfully sent </h1>
<p>{{post.title}} was successfullly sent to {{form.cleaned_data.to}}.</p>
{% else %}
<h1> Share {{post.title}} by email</h1>
<form method="post">
    {{form.as_p}}
    {% csrf_token %}
    <input type="submit" value="Send Email">
</form>

{% endif %}
{% endblock %}